### ISSUE TITLE
Build failure on linux-gnu-aarch64

### ISSUE THREAD

**Issue by liate7** [openbios/openbios#11]
Guix's `openbios-qemu-ppc` package currently fails to compile on aarch64 (64 bit arm).  (Issue thread [here](https://issues.guix.gnu.org/60719).)  After some investigation, it appears that the problem is that the eventual ./target/include/asm/types.h shadows <asm/types.h>, which is transitively included by <signal.h> on aarch64 (gcc version 10.3.0, linux headers 5.10.35).  When the necessary types aren't available, the build fails.

The failing guix build log is attached: [openbios-qemu-ppc-guix-build-log.txt](https://github.com/openbios/openbios/files/10431307/openbios-qemu-ppc-guix-build-log.txt); otherwise, I'm happy to post whatever other information I can.

**Comment by liate7** [comment]
...as it turns out, this issue was already fixed in af97fd7af5e7c18f591a7b987291d3db4ffb28b5; I really should have tested some more recent commits.  Sorry for the unnecessary issue.

**Comment by helinwang** [comment]
Hi @liate7 wanted to say thanks for your effort here and in the GNU mailing list. With your workaround I was able to run GUIX on my aarch64 VM and start the GUIX journey.

**Comment by mcayland** [comment]
@liate7 Thanks for the update. Are you sure it's the commit af97fd7 which fixed the issue for you? The reason for asking is that commit is pure Forth, so it has no visible effect other than to perhaps push things a bit further down in memory. I'd wonder if perhaps you are tickling a compiler bug somewhere, so it might be one to keep an eye on.

**Comment by liate7** [comment]
I am _absolutely_ not sure that af97fd7 fixed the issue; it 
probably would have been more correct to say that the issue was 
fixed _as of_ that commit.  That's the commit that guix upgraded 
to and fixed the issue for me, but I am not the one who upgraded 
the package and don't know why that commit in particular was 
chosen.  Given that the issue was that openbios's C code was 
shadowing a system header, thus preventing it from being included, 
I highly doubt that the forth change is at all related.

Thanks for checking, though
