### ISSUE TITLE
Bootlin toolchains build OpenBIOS on Sparc64, but cause QEMU to immediately abort

### ISSUE THREAD

**Issue by crass** [openbios/openbios#15]
These (and possibly all the others) [bootlin cross compile toolchains for sparc64](https://toolchains.bootlin.com/releases_sparc64.html) successfully compile OpenBIOS, but get the following QEMU abort: [sparc64--glibc--stable-2021.11-1](https://toolchains.bootlin.com/downloads/releases/toolchains/sparc64/tarballs/sparc64--glibc--stable-2021.11-1.tar.bz2) (GCC 10.3.0), [sparc64--glibc--stable-2021.11-1](https://toolchains.bootlin.com/downloads/releases/toolchains/sparc64/tarballs/sparc64--glibc--stable-2021.11-1.tar.bz2).

```
qemu: fatal: Trap 0x0064 while trap level (5) >= MAXTL (5), Error state
pc: 0000000000004c80  npc: 0000000000004c84
%g0-3: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
%g4-7: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
%o0-3: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
%o4-7: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
%l0-3: 0000000007f001d8 000001ff00000000 000001fff0080000 0000000000000000 
%l4-7: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
%i0-3: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
%i4-7: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
%f00:  0000000000000000 0000000000000000 0000000000000000 0000000000000000
%f08:  0000000000000000 0000000000000000 0000000000000000 0000000000000000
%f16:  0000000000000000 0000000000000000 0000000000000000 0000000000000000
%f24:  0000000000000000 0000000000000000 0000000000000000 0000000000000000
%f32:  0000000000000000 0000000000000000 0000000000000000 0000000000000000
%f40:  0000000000000000 0000000000000000 0000000000000000 0000000000000000
%f48:  0000000000000000 0000000000000000 0000000000000000 0000000000000000
%f56:  0000000000000000 0000000000000000 0000000000000000 0000000000000000
pstate: 00000414 ccr: 44 (icc: -Z-- xcc: -Z--) asi: 00 tl: 5 pil: 0 gl: 2
tbr: 0000000000000000 hpstate: 0000000000000000 htba: 0000000000000000
cansave: 6 canrestore: 0 otherwin: 0 wstate: 0 cleanwin: 6 cwp: 7
fsr: 0000000000000000 y: 0000000000000000 fprs: 0000000000000000

Aborted
```

The toolchain [GCC 10.3.0 toolchain](https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/10.3.0/x86_64-gcc-10.3.0-nolibc-sparc64-linux.tar.xz) from kernel.org runs fine in QEMU. While this is likely an issue with bootlin's build. I create this issue here for others who might run into this issue.

**Comment by mcayland** [comment]
Thanks for the report. I'd already noticed this when trying to integrate OpenBIOS into the QEMU build toolchain, which makes use of the Debian cross-compilers and they suffer from the same issue whereby the firmware builds but then promptly crashes.

For now my workaround has been the same as yours, which is to use the kernel toolchain to build the OpenBIOS binaries and that is used by GitHub actions when commits are pushed to master. As part of this process a builder image is generated and puhsed to GHCR for use my 3rd parties who wish to build OpenBIOS themselves.

An example invocation is shown below:

```
docker run --rm -it -v "$(pwd):/root" ghcr.io/openbios/openbios-builder:master \  
  /bin/bash -c "./config/scripts/switch-arch sparc64 && make"
```

At some point it would be useful to understand why the OpenBIOS binaries are failing, but it's something that will likely take me some time to investigate.

**Comment by mcayland** [comment]
As of current master, I am now able to build the OpenBIOS binaries using the standard Debian cross-compilers (there were some recent changes to the compiler flags that were required to make this work). Can you confirm that this is now working for you?

**Comment by mcayland** [comment]
Since it works for me, and I've heard no other feedback, I'm closing this issue.
