### ISSUE TITLE
README update required

### ISSUE THREAD

**Issue by brokensyntax** [openbios/openbios#17]
LinuxBIOS[.]org no longer exists   
   
The project is now (and has been for a while) coreboot found at coreboot.org   
The old domain appears to have been squatted now, and is not somewhere people looking for open BIOS firmware are likely to want to be  directed.

**Comment by mcayland** [comment]
Thanks for the heads-up. Patch posted at https://mail.coreboot.org/hyperkitty/list/openbios@openbios.org/thread/KJFALSQFF254GAGE3EGWLQ4TSJZRBHHE/.
