### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by arseholio** [openbios/openbios#5]
make
/usr/bin/xsltproc
Building OpenBIOS for amd64
Building...
error:
make[1]: Entering directory '/tmp/openbios/obj-amd64'
  CC    target/arch/unix/unix.o
/tmp/openbios/arch/unix/unix.c: In function ‘read_from_disk’:
/tmp/openbios/arch/unix/unix.c:420:2: error: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Werror=unused-result]
  read(diskemu, buf, size);
  ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
rules.mak:209: recipe for target 'target/arch/unix/unix.o' failed
make[1]: *** [target/arch/unix/unix.o] Error 1
make[1]: Leaving directory '/tmp/openbios/obj-amd64'
Makefile:19: recipe for target 'build' failed
make: *** [build] Error 1

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by MattK1989** [comment]
We commented out the read(diskemu, buf, size) command for our project and it compiled just fine. 

Another thing you can do is to go to openbios/Makefile.target. Somewhere around line 32, you'll see 'CFLAGS+= -Werror'. What this flag does is it tells the compiler to treat all warnings as errors (cc1: all warnings being treated as errors). Comment out this line and it should compile for you.

**Comment by mcayland** [comment]
This is now fixed in master.
